apiVersion: v1
kind: Service
metadata:
  name: workitout-service
  labels:
    app: workitout
spec:
  type: LoadBalancer
  selector:
    app: workitout
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
